--------------------------------------------------------
-- ELIMINACIÓN SEGURA DE TABLAS EXISTENTES
--------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_RESERVATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_COWORKING_SPACES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_SPACES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_SPACE_TYPES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_USUARIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_ROLES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN NULL; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.USUARIOS_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.ROLES_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.SPACE_TYPES_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.SPACES_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.COWORKING_SPACES_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.RESERVATIONS_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN NULL; END IF; END;
/

--------------------------------------------------------
-- CREACIÓN DE SECUENCIAS
--------------------------------------------------------
CREATE SEQUENCE UNA.USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.SPACE_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.SPACES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.COWORKING_SPACES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.RESERVATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

--------------------------------------------------------
-- CREACIÓN DE TABLAS
--------------------------------------------------------

CREATE TABLE UNA.TB_ROLES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    UNIQUE (NAME)
) TABLESPACE USERS;

CREATE TABLE UNA.TB_USUARIOS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    CORREO_ELECTRONICO VARCHAR2(150),
    VERSION NUMBER(19,0),
    CONSTRAINT UK_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES UNA.TB_ROLES(ID)
) TABLESPACE USERS;

CREATE TABLE UNA.TB_SPACE_TYPES (
    ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    UNIQUE (TYPE_NAME)
) TABLESPACE USERS;

CREATE TABLE UNA.TB_SPACES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CAPACITY NUMBER,
    ROW_INDEX NUMBER,
    COLUMN_INDEX NUMBER,
    ROW_SPAN NUMBER DEFAULT 1,
    COL_SPAN NUMBER DEFAULT 1,
    UNIQUE (NAME)
) TABLESPACE USERS;

CREATE TABLE UNA.TB_COWORKING_SPACES (
    ID NUMBER PRIMARY KEY,
    SPACE_ID NUMBER NOT NULL,
    TYPE_ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CAPACITY NUMBER,
    CONSTRAINT FK_COWORKING_SPACE FOREIGN KEY (SPACE_ID) REFERENCES UNA.TB_SPACES(ID),
    CONSTRAINT FK_COWORKING_TYPE FOREIGN KEY (TYPE_ID) REFERENCES UNA.TB_SPACE_TYPES(ID)
) TABLESPACE USERS;

CREATE TABLE UNA.TB_RESERVATIONS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER(19,0) NOT NULL,
    COWORKING_SPACE_ID NUMBER NOT NULL,
    START_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6) NOT NULL,
    IS_CANCELLED CHAR(1) DEFAULT 'N',
    VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_RESERVATION_USER FOREIGN KEY (USER_ID) REFERENCES UNA.TB_USUARIOS(ID),
    CONSTRAINT FK_RESERVATION_COWORKING FOREIGN KEY (COWORKING_SPACE_ID) REFERENCES UNA.TB_COWORKING_SPACES(ID)
) TABLESPACE USERS;
