--------------------------------------------------------
-- ELIMINACIÓN SEGURA DE TABLAS Y SECUENCIAS
--------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_RESERVATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_COWORKING_SPACES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_SPACES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_SPACE_TYPES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_USUARIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UNA.TB_ROLES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.USUARIOS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.ROLES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.SPACE_TYPES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.SPACES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.COWORKING_SPACES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE UNA.RESERVATIONS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--------------------------------------------------------
-- CREACIÓN DE SECUENCIAS
--------------------------------------------------------
CREATE SEQUENCE UNA.USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.SPACE_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.SPACES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.COWORKING_SPACES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UNA.RESERVATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

--------------------------------------------------------
-- CREACIÓN DE TABLAS
--------------------------------------------------------
CREATE TABLE UNA.TB_ROLES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    UNIQUE (NAME)
);

CREATE TABLE UNA.TB_USUARIOS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    CORREO_ELECTRONICO VARCHAR2(150),
    VERSION NUMBER(19,0),
    CONSTRAINT UK_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES UNA.TB_ROLES(ID)
);

CREATE TABLE UNA.TB_SPACE_TYPES (
    ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    UNIQUE (TYPE_NAME)
);

CREATE TABLE UNA.TB_SPACES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CAPACITY NUMBER,
    ROW_INDEX NUMBER,
    COLUMN_INDEX NUMBER,
    ROW_SPAN NUMBER DEFAULT 1,
    COL_SPAN NUMBER DEFAULT 1,
    UNIQUE (NAME)
);

CREATE TABLE UNA.TB_COWORKING_SPACES (
    ID NUMBER PRIMARY KEY,
    SPACE_ID NUMBER NOT NULL,
    TYPE_ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CAPACITY NUMBER,
    CONSTRAINT FK_COWORKING_SPACE FOREIGN KEY (SPACE_ID) REFERENCES UNA.TB_SPACES(ID),
    CONSTRAINT FK_COWORKING_TYPE FOREIGN KEY (TYPE_ID) REFERENCES UNA.TB_SPACE_TYPES(ID)
);

CREATE TABLE UNA.TB_RESERVATIONS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER(19,0) NOT NULL,
    COWORKING_SPACE_ID NUMBER NOT NULL,
    RESERVATION_DATE DATE,
    START_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6) NOT NULL,
    IS_CANCELLED CHAR(1) DEFAULT 'N',
    VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_RESERVATION_USER FOREIGN KEY (USER_ID) REFERENCES UNA.TB_USUARIOS(ID),
    CONSTRAINT FK_RESERVATION_COWORKING FOREIGN KEY (COWORKING_SPACE_ID) REFERENCES UNA.TB_COWORKING_SPACES(ID)
);

-- DATOS DE PRUEBA -------------------------------------
INSERT INTO UNA.TB_ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ADMIN');
INSERT INTO UNA.TB_ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'USER');

INSERT INTO UNA.TB_USUARIOS (ID, USERNAME, PASSWORD, ROLE_ID, IS_ACTIVE, VERSION, APELLIDO, CORREO_ELECTRONICO, NOMBRE) VALUES (
    USUARIOS_SEQ.NEXTVAL, 'admin', 'admin',
    (SELECT ID FROM UNA.TB_ROLES WHERE NAME = 'ADMIN'),
    'A', 1, 'Ramirez', 'admin@una.ac.cr', 'Carlos'
);
INSERT INTO UNA.TB_USUARIOS (ID, USERNAME, PASSWORD, ROLE_ID, IS_ACTIVE, VERSION, APELLIDO, CORREO_ELECTRONICO, NOMBRE) VALUES (
    USUARIOS_SEQ.NEXTVAL, 'una', 'una',
    (SELECT ID FROM UNA.TB_ROLES WHERE NAME = 'USER'),
    'A', 1, 'Sanchez', 'user1@una.ac.cr', 'Laura'
);

INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Oficina Privada');
INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Sala de Reuniones');
INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Área Común');

INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (SPACES_SEQ.NEXTVAL, 'Segundo Piso', 25);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (SPACES_SEQ.NEXTVAL, 'Planta Baja', 40);

INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (
    COWORKING_SPACES_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_SPACES WHERE NAME = 'Segundo Piso'),
    (SELECT ID FROM UNA.TB_SPACE_TYPES WHERE TYPE_NAME = 'Oficina Privada'),
    'Oficina 201', 3
);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (
    COWORKING_SPACES_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_SPACES WHERE NAME = 'Planta Baja'),
    (SELECT ID FROM UNA.TB_SPACE_TYPES WHERE TYPE_NAME = 'Sala de Reuniones'),
    'Sala A', 10
);

INSERT INTO UNA.TB_RESERVATIONS (ID, USER_ID, COWORKING_SPACE_ID, START_TIME, END_TIME, IS_CANCELLED, VERSION) VALUES (
    RESERVATIONS_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_USUARIOS WHERE USERNAME = 'admin'),
    (SELECT ID FROM UNA.TB_COWORKING_SPACES WHERE NAME = 'Oficina 201'),
    TO_TIMESTAMP('2025-06-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2025-06-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'N', 1
);
INSERT INTO UNA.TB_RESERVATIONS (ID, USER_ID, COWORKING_SPACE_ID, START_TIME, END_TIME, IS_CANCELLED, VERSION) VALUES (
    RESERVATIONS_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_USUARIOS WHERE USERNAME = 'una'),
    (SELECT ID FROM UNA.TB_COWORKING_SPACES WHERE NAME = 'Sala A'),
    TO_TIMESTAMP('2025-06-02 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2025-06-02 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'N', 1
);

COMMIT;
