--------------------------------------------------------
-- DATOS DE PRUEBA
--------------------------------------------------------

-- TB_ROLES
INSERT INTO UNA.TB_ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ADMIN');
INSERT INTO UNA.TB_ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'USER');

-- TB_USUARIOS
INSERT INTO UNA.TB_USUARIOS (
    ID, USERNAME, PASSWORD, ROLE_ID, IS_ACTIVE, VERSION,
    APELLIDO, CORREO_ELECTRONICO, NOMBRE
) VALUES (
    USUARIOS_SEQ.NEXTVAL, 'admin', 'admin',
    (SELECT ID FROM UNA.TB_ROLES WHERE NAME = 'ADMIN'),
    'A', 1, 'Ramirez', 'admin@una.ac.cr', 'Carlos'
);

INSERT INTO UNA.TB_USUARIOS (
    ID, USERNAME, PASSWORD, ROLE_ID, IS_ACTIVE, VERSION,
    APELLIDO, CORREO_ELECTRONICO, NOMBRE
) VALUES (
    USUARIOS_SEQ.NEXTVAL, 'una', 'una',
    (SELECT ID FROM UNA.TB_ROLES WHERE NAME = 'USER'),
    'A', 1, 'Sanchez', 'user1@una.ac.cr', 'Laura'
);

-- TB_SPACE_TYPES
INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Oficina Privada');
INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Sala de Reuniones');
INSERT INTO UNA.TB_SPACE_TYPES (ID, TYPE_NAME) VALUES (SPACE_TYPES_SEQ.NEXTVAL, 'Área Común');

-- TB_SPACES  (piso base)
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (SPACES_SEQ.NEXTVAL, 'Segundo Piso', 25);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (SPACES_SEQ.NEXTVAL, 'Planta Baja', 40);

-- TB_COWORKING_SPACES  (ejemplos iniciales)
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (
    COWORKING_SPACES_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_SPACES WHERE NAME = 'Segundo Piso'),
    (SELECT ID FROM UNA.TB_SPACE_TYPES WHERE TYPE_NAME = 'Oficina Privada'),
    'Oficina 201', 3
);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (
    COWORKING_SPACES_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_SPACES WHERE NAME = 'Planta Baja'),
    (SELECT ID FROM UNA.TB_SPACE_TYPES WHERE TYPE_NAME = 'Sala de Reuniones'),
    'Sala A', 10
);

-- TB_RESERVATIONS  (primeros registros)
INSERT INTO UNA.TB_RESERVATIONS (
    ID, USER_ID, COWORKING_SPACE_ID, START_TIME, END_TIME, IS_CANCELLED, VERSION
) VALUES (
    RESERVATIONS_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_USUARIOS WHERE USERNAME = 'admin'),
    (SELECT ID FROM UNA.TB_COWORKING_SPACES WHERE NAME = 'Oficina 201'),
    TO_TIMESTAMP('2025-06-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2025-06-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'N', 1
);

INSERT INTO UNA.TB_RESERVATIONS (
    ID, USER_ID, COWORKING_SPACE_ID, START_TIME, END_TIME, IS_CANCELLED, VERSION
) VALUES (
    RESERVATIONS_SEQ.NEXTVAL,
    (SELECT ID FROM UNA.TB_USUARIOS WHERE USERNAME = 'una'),
    (SELECT ID FROM UNA.TB_COWORKING_SPACES WHERE NAME = 'Sala A'),
    TO_TIMESTAMP('2025-06-02 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2025-06-02 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'N', 1
);

-- Detalle de espacios y coworking del Piso 1
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (3,  'P1_E1',           1);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (4,  'P1_E2',           1);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (5,  'Área común P1_1', 2);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (6,  'Área común P1_2', 2);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (7,  'Sala P1_A',       6);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (8,  'Área común P1_3', 2);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (9,  'P1_E3',           1);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (10, 'P1_E4',           1);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (11, 'Sala P1_B',       6);
INSERT INTO UNA.TB_SPACES (ID, NAME, CAPACITY) VALUES (12, 'Área común P1_4', 2);

INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (3,  3,  1, 'Oficina P1_E1',      1);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (4,  4,  1, 'Oficina P1_E2',      1);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (5,  5,  3, 'Área común P1_1',    2);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (6,  6,  3, 'Área común P1_2',    2);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (7,  7,  2, 'Sala P1_A',          6);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (8,  8,  3, 'Área común P1_3',    2);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (9,  9,  1, 'Oficina P1_E3',      1);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (10, 10, 1, 'Oficina P1_E4',      1);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (11, 11, 2, 'Sala P1_B',          6);
INSERT INTO UNA.TB_COWORKING_SPACES (ID, SPACE_ID, TYPE_ID, NAME, CAPACITY) VALUES (12, 12, 3, 'Área común P1_4',    2);

--------------------------------------------------------
-- AJUSTE VERSION EN COWORKING_SPACES
--------------------------------------------------------
UPDATE UNA.TB_COWORKING_SPACES
    SET VERSION = 0
    WHERE VERSION IS NULL;

COMMIT;